#ifndef RENDERLOO_SHADERS_INCLUDE_CONSTANTS_HPP
#define RENDERLOO_SHADERS_INCLUDE_CONSTANTS_HPP

#define BONES_MAX_COUNT 200
#define BONES_MAX_INFLUENCE 4
#define SHADER_LIGHTS_MAX 12
#define SHADER_SHADOWED_DIRECTIONAL_LIGHTS_MAX 1

#endif /* RENDERLOO_SHADERS_INCLUDE_CONSTANTS_HPP */
