#ifndef RENDERLOO_SHADERS_INCLUDE_CONSTANTS_HPP
#define RENDERLOO_SHADERS_INCLUDE_CONSTANTS_HPP

#define BONES_MAX_COUNT 200
#define BONES_MAX_INFLUENCE 4

#endif /* RENDERLOO_SHADERS_INCLUDE_CONSTANTS_HPP */
